-- SESSION #1
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN;

-- SESSION #2
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN;

-- SESSION #1
SELECT * FROM pizzeria
WHERE name = 'Pizza Hut';

-- SESSION #2
UPDATE pizzeria SET rating = 3.0 WHERE name = 'Pizza Hut';
COMMIT;

-- SESSION #1
SELECT * FROM pizzeria
WHERE name = 'Pizza Hut';

-- SESSION #1
COMMIT;
SELECT * FROM pizzeria
WHERE name = 'Pizza Hut';

-- SESSION #2
SELECT * FROM pizzeria
WHERE name = 'Pizza Hut';
